### ISSUE TITLE
Allow adding directories with content to existing archive

### ISSUE THREAD

**Issue by tkrajacic** [weichsel/ZIPFoundation#121] opened 2019-05-14 15:06 UTC
**Is your feature request related to a problem? Please describe.**
I tried updating an archive and add a directory and its contents (recursively). Using `archive.addEntry(…)`. I managed to get the directory entry to be included but it was empty.

**Describe the solution you'd like**
I would expect that providing a directory to `addEntry(…)` will add all its content as well.

**Describe alternatives you've considered**
I considered using FileManager to iterate over all the content and then calling `addEntry` for each item manually, but for now I could use `zipItem` on the directory and then opening the archive to add extra files as siblings to the zipped directory.

**Additional context**
Maybe I am missing something here and this should be possible already? It seems like this is obvious and I am doing something wrong.

**Comment by levigroker** [comment] 2019-05-14 22:49
So... I investigated this a bit as I too found this a bit strange. If you look at the code this behavior is "by design" though I think it could be improved.

I believe the intention is to use the `addEntry` method to create "low level" archive entries, as one might create an index in a book, where there's a desire to be able to create a directory "entry" and then subsequent calls would be made to add file entries within that directory entry. This is, in fact, exactly how the code within FileManager+ZIP behaves, and most certainly why this is written in this way.

That said, this could be improved. Firstly, in order to add a directory archive entry this API requires the directory to exist on the filesystem (related to #122 ) but this should not be a requirement for a low level API such as this is intended to be.

Additionally, there's presently no way to easily add a directory and its contents to an archive, as @tkrajacic rightly points out, and as this is a common use case I would expect an API to accommodate this capability.

**Comment by weichsel** [comment] 2019-05-15 12:58
Yes, as @levigroker already pointed out, `addEntry` is intended to add a _ZIP_ entry, which does not directly map to a file system item.  
ZIP has no concept of hierarchy. All entries are are a list of paths (+ metadata) that do not maintain a parent-child relationship of any sort. Directory entries in ZIP archives have the sole purpose of storing metadata for items that will be translated to file system directories during unzipping.  
Additionally, directory entries are optional within an archive. It's valid to store an entry with a nested path without providing directory entries for the intermediate directories. The implementation needs to take care to re-create the parent directory structure during unzipping.  

I understand that this behavior is confusing. We provide the `zipItem` method in the `FileManager` extension to provide a more convenient method to zip directories.  
Your special case, where you want to add an additional directory to an existing archive is not covered by this and the workaround you described - enumerating the additional directory contents and adding entries via `addEntry` - is currently the only supported way to add directories to existing archives.

**Comment by tkrajacic** [comment] 2019-05-15 13:36
Thank you both for the comprehensive replies!

> Your special case, where you want to add an additional directory…

I wonder if this is really such a special case 🤔. Otherwise it would be nice to have a convenience method provided.

**Comment by levigroker** [comment] 2019-05-15 19:50
Here's an extension which does what I need @tkrajacic ... you may find it useful as well. I would also be curious if a pull request with this (or close) would be welcome (@weichsel)

    public extension Archive {

      func add(url: URL, baseURL: URL? = nil, compressionMethod: CompressionMethod = .none, filter: ((URL) -> Bool) = { _ in return true }) throws {
        let include = filter(url)
        if include {
          let finalBaseURL = baseURL ?? url.deletingLastPathComponent()
          if let path = url.remainingPath(from: finalBaseURL) {
            try addEntry(with: path, relativeTo: finalBaseURL, compressionMethod: compressionMethod)
          }

          if let isDirectory = try? url.resourceValues(forKeys: [.isDirectoryKey]).isDirectory {
            if isDirectory {
              let items = try FileManager.default.contentsOfDirectory(at: url, includingPropertiesForKeys: [.isDirectoryKey])
              for item in items {
                try add(url: item, baseURL: finalBaseURL, compressionMethod: compressionMethod, filter: filter)
              }
            }
          }
        }
      }

    }

    public extension URL {
      func remainingPath(from base: URL) -> String? {
        // Ensure that both URLs represent files
        guard isFileURL && base.isFileURL else {
          return nil
        }

        // Standardize and make paths absolute
        let ourClean = standardizedFileURL.absoluteURL
        let baseClean = base.standardizedFileURL.absoluteURL
        let ourComps = ourClean.pathComponents
        let baseComps = baseClean.pathComponents

        if baseComps.count > ourComps.count {
          return ourClean.path
        }

        for i in 0 ..< baseComps.count {
          if baseComps[i] != ourComps[i] {
            return ourClean.path
          }
        }
        let remainderComps = ourComps[baseComps.count ..< ourComps.endIndex]
        return remainderComps.joined(separator: "/")
      }
    }

**Comment by levigroker** [comment] 2019-05-15 19:52
As a related side note, if we address #122 the `filter` method could return an optional path in the archive (different path and/or filename) instead of a simple boolean.

**Comment by weichsel** [comment] 2019-05-17 18:15
> I wonder if this is really such a special case 🤔. Otherwise it would be nice to have a convenience method provided.
I understand that the current implementation can be confusing and that a more convenient way to add entire directories would be a better fit for API users.  

I'd like to solve that problem, but that requires a refactoring which adds "batch" capabilities to the library. (where add & remove accept lists of URLs so that we can process the entries in a performant way. This is especially important for removal operations).  

I see this as a post 1.0 feature so I will close this issue for now.  

@levigroker Thank you for providing code to work around the API limitation. I will redirect users that face this problem to this issue.

**Closed by weichsel** 2019-05-17 18:15 UTC
