### ISSUE TITLE
Error Unzip a file zipped with "shouldKeeyParent = false" 

### ISSUE THREAD

**Issue by Fahrenberg** [weichsel/ZIPFoundation#280] opened 2023-07-03 15:18 UTC
# Summary
I'm zipping with shouldKeepParent: false into a existing folder
Unzipping this file results in a error and aborts unzipping.

zipping without shouldKeepParent works obviously as the directory is newly created by ZIPFoundation.

# Steps to Reproduce
Zip with 
```
try fm.zipItem(at: iCloudFilesURL, to: iCloudZipFile, shouldKeepParent: false)
```
unzip with 
```
do {
    try fm.unzipItem(at: iCloudZipFile, to: iCloudExtractURL)
} catch {
    print(error)
}
```
# Expected Results
adding all files in zip

# Actual Results
aborts after trying add .DS_Store
```
Error Domain=NSCocoaErrorDomain Code=516 "The file “.DS_Store” couldn’t be saved in the folder “Extract” because a file with the same name already exists." UserInfo={NSFilePath=/Users/JeanNicolas/Library/Mobile Documents/com~apple~CloudDocs/Programmierung/Swift/Test/Zipping/Extract/.DS_Store}
```

# Regression & Version

# Related Link

**Comment by weichsel** [comment] 2023-12-31 09:31
Duplicate of https://github.com/weichsel/ZIPFoundation/issues/54

**Closed by weichsel** 2023-12-31 09:31 UTC
