### ISSUE TITLE
ZIP (Created by 7z (64bit)) can't unzip

### ISSUE THREAD

**Issue by dsa28s** [weichsel/ZIPFoundation#72] opened 2018-06-19 06:57 UTC
# Summary
Hello. Using the ZIPFoundation library, I found a problem that could not be unzip.
Created ZIP file by 7za (64Bit / Linux).
But, in iOS device, archive entry not shown, and can't unzip + not handling error. 

# Steps to Reproduce
```swift
try fileManager.unzipItem(at: zipURL, to: unzipFolderURL) // not working
            
if let archive = Archive(url: zipURL, accessMode: .read) {
    archive.forEach({ (entry) in
        print(entry.path) // not printed
    })
}
```

# Expected Results
Unzip successfully.

# Actual Results
There was empty response.

# Regression & Version
0.9.0

# Related Link

**Comment by weichsel** [comment] 2018-06-19 07:50
Hello,

This is most likely a duplicate of https://github.com/weichsel/ZIPFoundation/issues/69
ZIP Foundation currently does not support ZIP64 archives. You can test if your file is ZIP64 by setting a breakpoint in `CentralDirectoryStructure.isZIP64` check the return value of that property.

**Comment by dsa28s** [comment] 2018-06-19 08:30
Thanks!

**Closed** 2018-06-19 08:30 UTC
