### ISSUE TITLE
SIGABRT when importing ZIPFoundation using Carthage by a library

### ISSUE THREAD

**Issue by philips77** [weichsel/ZIPFoundation#112] opened 2019-04-12 07:21 UTC
Hi,
I have gotten an issue https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/issues/281, where some users who use Carthage for managing dependencies have troubles with using the library. DFU Lib is using ZIPFoundation since version 4.3.0, before we were depending on [Zip](https://github.com/marmelroy/Zip).
I don't know if the issue is in the DFU library, or ZIPFoundation, or it's just a configuration issue, but perhaps you have seen such case before and could help us. Thank you!

**Comment by weichsel** [comment] 2019-04-12 09:10
Hi,

I recently merged a PR from a user who also had problems with ZIP Foundation when used from the `IOS-Pods-DFU-Library`: https://github.com/weichsel/ZIPFoundation/pull/91 
But in the above case, the user mentions in the comments, that he is not using any ZIP functionality and the PR only fixed a library load error.  

So I suppose there is something else going on here:  
I created a small test project, that consumes DFU Lib via Carthage and was able to reproduce the crash where the dynamic linker is unable to find the symbol `sSo13NSFileManagerC13ZIPFoundationE9unzipItem2at2to8progressy10Foundation3URLV_AJSo10NSProgressCSgtKF`. The reason for that is, that the new ZIP Foundation version did get a new _optional_ parameter for this method (`preferredEncoding`). So the mangled signature for this method now reads:
`sSo13NSFileManagerC13ZIPFoundationE9unzipItem2at2to8progress17preferredEncodingy10Foundation3URLV_AKSo10NSProgressCSgSSAIE0J0VSgtKF`.  
You library seems to link against an old version (0.9.8 or older) of ZIP Foundation, that has been checked into your source tree. So at compile time everything looks good: The API is unchanged (because the new parameter is optional) and the CocoaPods framework target provides the (old) symbol.  
But at runtime - when integrating via Carthage - the new built ZIPFoundation 0.9.9 framework gets loaded and this one does not contain the old symbol.

**Comment by philips77** [comment] 2019-04-12 10:36
Thank you very much for the help. So you say, that switching to 0.9.9 should solve the issue?

**Comment by weichsel** [comment] 2019-04-12 10:55
I haven't tried it but, yes, I think if you update the ZIP Foundation sources that are part of your source tree, the compiler should emit symbols with the same mangled names.  

I don't fully understand your dependency management setup and I also don't know your requirements, but your current solution seems a bit test & maintenance intensive.  
You currently have to make sure that the ZIP Foundation version, that CocoaPods uses when building DFU lib is always the same that Carthage will use when some 3rd party consumer integrates your library. IMO this is impossible if you have copy of ZIPFoundation (at a certain version) checked into your source tree and a Cartfile that allows all versions.

**Closed** 2019-04-17 17:59 UTC
