### ISSUE TITLE
When creating a in-memory archive Entries can not be remove/replaced.

### ISSUE THREAD

**Issue by gooswa** [weichsel/ZIPFoundation#222] opened 2021-05-03 00:38 UTC
# Summary

Using `ZIPFoundation` to store a Zipped type document bundle. If a file is read and stored in an `Archive` using the in-memory method `Archive(data: fileData, accessMode: .update)` then later you attempt to to save that same `Archive` to disk using  `archive.data` you can't replace an `Entry` or by attempting to removing it  first if it exists.

Also if you attempt to use just `addEntry` and use the same  path it creates two entries and then doubles the size of the archive since there are two entries of the same `Entry`, even if you use the same path as the previous entry.

# Steps to Reproduce

# Expected Results

# Actual Results

# Regression & Version

# Related Link

**Comment by weichsel** [comment] 2021-05-03 05:24
> Using ZIPFoundation to store a Zipped type document bundle. If a file is read and stored in an Archive using the in-memory method Archive(data: fileData, accessMode: .update) then later you attempt to to save that same Archive to disk using archive.data you can't replace an Entry or by attempting to removing it first if it exists.

Can you share the code that you are using to create/modify your archive?

> Also if you attempt to use just addEntry and use the same path it creates two entries and then doubles the size of the archive since there are two entries of the same Entry, even if you use the same path as the previous entry.

This is expected. The ZIP specification does not enforce uniqueness of paths. It's valid to store multiple entries with the same path. When you are using subscripting to obtain entries with that path, ZIP Foundation returns the first one.

**Comment by gooswa** [comment] 2021-05-03 06:37
Yeah I will recreate it. Give me a day. I was using a document type app to create an `Archive` from a `FileWrapper`.

**Comment by gooswa** [comment] 2021-05-03 15:41
Here is a sample project I made. I would find this use case to be pretty common if wanted to continue to use an in-memory `Archive`. Since I would want to update the archive and save it back.

I totally understand if the ZIP specification does not enforce this but I would think most common scenario would be that people are defining paths as a way to control a "folder" type structure, even though a zip file is not truly a folder structure. 

I would think allowing to removing an `Entry` in a in-memory `Archive` before replacing it would be a great compromise to allow this to happen.

https://github.com/gooswa/ArchiveDoc

**Comment by weichsel** [comment] 2021-05-04 05:54
Thanks for providing the sample - Helped a lot to reproduce the problem.

This is a bug in in ZIP Foundation that you uncovered here: We currently don't handle the "remove" case properly for in-memory archives. This was an oversight on my side when I reviewed and merged the PR that contributed in-memory archives. 

The underlying issue comes from the way that we handle entry removal (below is a quote from a reply to [another issue](https://github.com/weichsel/ZIPFoundation/issues/221)):
> ZIP files are organized as "sequence of files" with some interleaved metadata and a central directory structure (at the end of the file) that maintains additional metadata and offsets.
When an entry gets removed, all subsequent entries have to be rewritten and the central directory must be updated to contain the new offsets.
ZIP Foundation does that by streaming all entries of an archive to a temp location, skipping the entry that should be removed. After it reaches the end of the archive, it replaces the old archive with the new one.

The error is happening during the replace. Since in-memory archives don't have a backing file URL, we use a URL scheme (`memory://`) to indicate that this is a "special" archive. The `FileManager` call that replaces the original archive with the temporary one then stumbles, because the original archive does not have a proper file URL 🤦‍♂️.

I currently don't have time to provide a quick fix, but if you want to give it a shot, here's what you could try:
1. In `Archive.remove` init a new temporary in-memory `Archive` instead of a file based archive at a temp location.
2. Instead of calling `Archive.replaceCurrentArchiveWithArchive`, add another helper that uses `Archive.configureMemoryBacking` to obtain a new memory file descriptor. You'll have to pass in `data` of the temp archive and assign the returned tuple to `self.archiveFile` and `self.memoryFile`.

**Closed** 2021-05-11 06:34 UTC

**Comment by weichsel** [comment] 2021-05-11 07:12
This is now fixed on `development`.
